[FIX] Do not emit on disconnect
Prior to this commit, a "disconnect" signal was emitted in response to
handling a disconnect request.  However, in cases where a disconnect
request occurs due to an exception, attempting to emit a signal may
result in endless recursion, causing the server to crash, as show below:

      ...
      File "site-packages\engineio\socket.py", line 101, in close
        self.server._trigger_event('disconnect', self.sid, async=False)
      File "site-packages\engineio\server.py", line 357, in _trigger_event
        return self.handlers[event](*args)
      File "site-packages\socketio\server.py", line 502, in _handle_eio_disconnect
        self._handle_disconnect(sid, '/')
      File "site-packages\socketio\server.py", line 411, in _handle_disconnect
        self._trigger_event('disconnect', n, sid)
      File "site-packages\socketio\server.py", line 460, in _trigger_event
        return self.handlers[namespace][event](*args)
      File "zmq_plugin_bridge\app.py", line 34, in disconnect
        namespace=NAMESPACE)
      File "site-packages\socketio\server.py", line 206, in emit
        room or 'all', namespace)
    RuntimeError: maximum recursion depth exceeded

As of this commit, no signal is emitted on disconnect to avoid this
issue.